# Expor endpoints de métricas para acesso da Máquina 2
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-metrics
  namespace: default
  labels:
    app: kubernetes-metrics
spec:
  type: NodePort
  ports:
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30443  # API Server metrics
    protocol: TCP
  selector:
    component: kube-apiserver
---
# Endpoint para métricas do kubelet
apiVersion: v1
kind: Service
metadata:
  name: kubelet-metrics
  namespace: kube-system
  labels:
    app: kubelet-metrics
spec:
  type: NodePort
  ports:
  - name: kubelet-metrics
    port: 10250
    targetPort: 10250
    nodePort: 30250  # Kubelet metrics
    protocol: TCP
  selector:
    app: kubelet
---
# Service para expor métricas do cadvisor
apiVersion: v1
kind: Service
metadata:
  name: cadvisor-metrics
  namespace: kube-system
  labels:
    app: cadvisor-metrics
spec:
  type: NodePort
  ports:
  - name: cadvisor
    port: 4194
    targetPort: 4194
    nodePort: 30194  # cAdvisor metrics
    protocol: TCP
  selector:
    app: cadvisor