services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST_BACKEND: backend
      PORT_BACKEND: 5000
    depends_on:
      - backend
    
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./banco_de_dados/:/docker-entrypoint-initdb.d/
    env_file:
      - .env