version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  db:
    image: postgres:latest
    container_name: patocash_db
    restart: always
    environment:
      POSTGRES_DB: patocash
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql