apiVersion: apps/v1
kind: Deployment
metadata:
  name: patocast-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patocast-frontend
  template:
    metadata:
      labels:
        app: patocast-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: nodejs-app
        image: patocast-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: HOST_BACKEND
          valueFrom:
            configMapKeyRef:
              name: patocast-config
              key: HOST_BACKEND
        - name: PORT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: patocast-config
              key: PORT_BACKEND
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: patocast-config
              key: NODE_ENV
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: patocast-frontend-service
spec:
  selector:
    app: patocast-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort